### ISSUE TITLE
Eta for Visual Studio 2022 Support

### ISSUE THREAD

**Issue by user1568891** [haacked/Encourage#52]
Would love to see this for Visual Studio 2022. Currently it won't let me install to it.

**Comment by CalvinAllen** [comment]
Going to attempt a PR to support 2022, stay tuned :)

**Comment by CalvinAllen** [comment]
@haacked - I've got the project restructured to support this, but running into issues getting the 2022 version to work.

Almost all of the core code has been moved into a Shared project, and is referenced by a project targeting x86 (this is the original version), and a new x64 project.  The x86 version seems to (still) work fine in AT LEAST 2017 and 2019 (I no longer have access to any older than that).  x64 seems to install into 2022, but never fires on save, nor is the settings dialog page available.  

I'm out of my depth troubleshooting it, since I'm not familiar with the SDKs you're using / needed, nor interacting with the editor.  Seems like something might have changed between 2019 and 2022 that is causing it, but I'm not sure. Might need to see if somebody else can help on that part.

You'll have to deploy two versions of the extension with the changes, one for everything up to 2019, and another for 2022+.

**Comment by CalvinAllen** [comment]
LOL, I said that and then immediately figured out the issue.  Of course.

The new project, even though it was a VSIX, wasn't really doing any VSIX "stuff".  Now it seems to be working okay!

**Comment by pmcintyre3** [comment]
Just upgraded to VS 2022 and didn't see it available in the extension manager. Did this ever get pushed to the marketplace for 2022?

**Comment by pmcintyre3** [comment]
Nice!! I actually built it locally and installed it. But I'll definitely use this listing for the next time I build a new environment. Thank you!

**Comment by CalvinAllen** [comment]
And we are done!

2012-2019 version is here - https://marketplace.visualstudio.com/items?itemName=Haacked.Encourage

2022 (and up?) version is here - https://marketplace.visualstudio.com/items?itemName=Haacked.Encourage-22

Officially closing issue 🎉🥳🎈🎊🍾

**Comment by haacked** [comment]
Thank you!
